language: ruby

services:
  - docker
before_install:
  - docker build --build-arg symbol=EOS --build-arg branch=$TRAVIS_BRANCH -t liquidapps/eosio-plugins:$TRAVIS_BRANCH .
script:
  - bash docker_push
